### ISSUE TITLE
Restarting fafnir causes dk.acto.fafnir.api.exception.PasswordDecryptionFailed: null exception

### ISSUE THREAD

**Issue by benjaminant** [actoaps/fafnir-sso#13]
Restarting fafnir-sso docker container results in PasswordDecryptionFailed null exception. 

I will be attaching the stack trace below. I believe it is related to the jks file being re-created on every container restart hence resulting in a key mismatch. The docker volume is mounted on the correct directory as well (var/lib/fafnir). 

I have also noticed that the keystore password is always empty even thought I have the **KEY_PASS** & **KEYSTORE_PASS** env variables set up.

I use Windows for development and all of the container restarts etc. are done through Docker Desktop. 

[stacktrace.txt](https://github.com/actoaps/fafnir-sso/files/6357574/stacktrace.txt)

Please let me know if I should provide additional information.

**Comment by FlameDuck** [comment]
Hi mate,

Thanks a lot for reporting this issue. We have reproduced the issue and are currently working on releasing a new version with the fixes.

**Comment by benjaminant** [comment]
Thanks a lot for the quick and efficient response guys.
